import './globals.css';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { isAdmin } from '../database/admins';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/logoutButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type Props = { children: ReactNode };
export default async function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  props: Props,
) {
  const cookieStore = cookies();
  const tokenSeession = cookies().get('sessionToken');
  console.log('tokenSeession', tokenSeession);

  const user =
    tokenSeession && (await getUserBySessionToken(tokenSeession.value));
  const isadmin = await isAdmin(user?.id);
  console.log('tokenSeession user', user);

  return (
    <html lang="en">
      <body>
        <header className="bg-white" aria-label="Global">
          <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8">
            <div className="mx-auto  p-6 ">
              <Link href="/" className="mt-1 block font-semibold text-gray-900">
                Home
              </Link>
            </div>
            <div className="mx-auto flex   p-6 ">
              {user ? (
                <>
                  <div className="mt-1 block font-semibold text-gray-900">
                    Hallo {user.username}
                  </div>
                  <LogoutButton />
                  <Link
                    href={`/profile/${user.username}`}
                    className="mt-1 block font-semibold text-gray-900"
                  >
                    Profile
                  </Link>
                  <Link
                    href="/newposts"
                    className="mt-1 block font-semibold text-gray-900"
                  >
                    Newposts
                  </Link>
                  {isadmin ? (
                    <Link
                      href="/admin"
                      className="mt-1 block font-semibold text-gray-900"
                    >
                      Admin
                    </Link>
                  ) : null}
                </>
              ) : (
                <>
                  <Link
                    href="/register"
                    className="mt-1 block font-semibold text-gray-900"
                  >
                    Register
                  </Link>
                  <Link
                    href="/login"
                    className="mt-1 block font-semibold text-gray-900"
                  >
                    Log in
                  </Link>
                </>
              )}
            </div>
          </nav>
        </header>
      </body>
      {children}
    </html>
  );
}
